# Generated by Django 6.0.2 on 2026-02-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_tags_unique_together_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='tags',
        ),
        migrations.AddField(
            model_name='people',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='people.tags'),
        ),
    ]
