# Generated by Django 6.0.2 on 2026-02-14 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_people_tags_people_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credit_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
